# Generated by Django 6.0.3 on 2026-03-11 14:34

import apps.tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(default=apps.tickets.models.generate_reference_id, editable=False, max_length=20, unique=True)),
                ('tracking_password', models.CharField(default=apps.tickets.models.generate_tracking_password, editable=False, max_length=100)),
                ('requester_email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to=apps.tickets.models.ticket_attachment_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['-date_created'],
            },
        ),
    ]
