# Generated by Django 4.2 on 2026-03-16 02:00

import apps.tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ulid',
            field=models.CharField(default=apps.tickets.models.generate_ulid, editable=False, max_length=26, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
