# Generated by Django 4.2 on 2026-03-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_ulid_alter_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='requester_full_name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
