# Generated by Django 4.2 on 2026-03-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_requester_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='requester_full_name',
            field=models.CharField(max_length=255),
        ),
    ]
