# Generated by Django 6.0.3 on 2026-03-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'offices',
                'ordering': ['name'],
            },
        ),
    ]
